before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: ['386', amd64, arm, arm64]
archives:
  - format: binary
release:
  prerelease: auto
snapshot:
  name_template: snapshot-{{.Commit}}
changelog:
  groups:
    - title: Features
      regexp: '^feat[(\\w)]?: .+$'
      order: 0
    - title: Bug fixes
      regexp: '^fix[(\\w)]?: .+$'
      order: 1
    - title: Others
      order: 999
