name: CI/CD

on:
  push:
    paths-ignore:
      - README.md
      - renovate.json
      - LICENSE
  pull_request:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # renovate: tag=v2
        with:
          version: v1.30
      - uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # renovate: tag=v2
        with:
          go-version: "1.15"
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
        with:
          fetch-depth: 0
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: goreleaser/goreleaser-action@5a54d7e660bda43b405e8463261b3d25631ffe86 # renovate: tag=v2
        with:
          args: build --rm-dist --snapshot
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@5a54d7e660bda43b405e8463261b3d25631ffe86 # renovate: tag=v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
