name: CI/CD

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore
      - .github/renovate.json
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: go test -v ./...
      - uses: golangci/golangci-lint-action@v3
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: goreleaser/goreleaser-action@v5
        with:
          args: build --rm-dist --snapshot
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
